### PR TITLE
Extend documentation of historical.process()

### PR DESCRIPTION
**Pull request by francescolovat**
When trying to retrieve data from `T000.csv`, it was not fully clear how to do so in an efficient manner. When reading historical.process() [docu](https://transportenergy.readthedocs.io/en/latest/historical.html?highlight=historical.process#item.historical.process), information about that function was missing and what was exactly the format of its argument `id`.

This PR extends its docstring and add example of `id` argument.

### CODE REVIEW

**Comment by khaeru** [comment]
Thanks @francescolovat!

The check failures here are unrelated to your PR, so I will make another to fix them and then ask you to rebase.

**Comment by khaeru** [comment]
#64 is merged, so please rebase.

**Comment by francescolovat** [comment]
> 
> 
> #64 is merged, so please rebase.

@khaeru thanks. Ready to merge now.

**Comment by khaeru** [comment]
The check failures here are because this a PR from a fork which has no access to the secret key used to upload data to our Google Cloud Storage bucket. I will open a separate issue to disable this.

**Pull request merged**
